// src/mockData.js

export const plantsData = [
  // --- FLOWERS ---
  {
    id: "lavender",
    name: "English Lavender",
    scientificName: "Lavandula angustifolia",
    category: "flower",
    sunlight: "Full Sun",
    waterFrequency: "Low",
    soilType: "Sandy, Well-draining",
    bloomSeason: "Summer",
    edible: true,
    difficulty: "Easy",
    commonPests: ["Spittlebugs", "Aphids"],
    description: "An aromatic evergreen shrub prized for its soothing fragrance, purple flower spikes, and essential oil production.",
    imageUrl: "/lavender.jpg"
  },
  {
    id: "peace-lily",
    name: "Peace Lily",
    scientificName: "Spathiphyllum wallisii",
    category: "flower",
    sunlight: "Full Shade",
    waterFrequency: "Moderate",
    soilType: "Loamy, Moist",
    bloomSeason: "Spring",
    edible: false,
    difficulty: "Easy",
    commonPests: ["Mealybugs", "Spider Mites"],
    description: "A popular tropical houseplant with glossy dark green leaves and elegant white spathes.",
    imageUrl: "/peace_lily.jpg"
  },
  {
    id: "sunflower",
    name: "Golden Sunflower",
    scientificName: "Helianthus annuus",
    category: "flower",
    sunlight: "Full Sun",
    waterFrequency: "Moderate",
    soilType: "Rich, Well-draining",
    bloomSeason: "Summer",
    edible: true,
    difficulty: "Easy",
    commonPests: ["Cutworms", "Sunflower Moths"],
    description: "Fast-growing annual with vibrant yellow flower heads that track the sun across the sky.",
    imageUrl: "https://images.unsplash.com/photo-1597848212624-a19eb35e2651?w=600&auto=format&fit=crop"
  },
  {
    id: "orchid",
    name: "Moth Orchid",
    scientificName: "Phalaenopsis",
    category: "flower",
    sunlight: "Partial Shade",
    waterFrequency: "Low",
    soilType: "Bark Chips, Sphagnum",
    bloomSeason: "Winter",
    edible: false,
    difficulty: "Moderate",
    commonPests: ["Scale", "Thrips"],
    description: "Stunning long-lasting bloomer featuring delicate moth-shaped blossoms in various hues.",
    imageUrl: "https://images.unsplash.com/photo-1525310072745-f49212b5ac6d?w=600&auto=format&fit=crop"
  },
  {
    id: "rose",
    name: "Hybrid Tea Rose",
    scientificName: "Rosa x hybrida",
    category: "flower",
    sunlight: "Full Sun",
    waterFrequency: "Moderate",
    soilType: "Rich Clay-Loam",
    bloomSeason: "Spring",
    edible: true,
    difficulty: "Hard",
    commonPests: ["Aphids", "Black Spot Fungus"],
    description: "Classic fragrant garden bloomer with intricate layered petals and sharp thorns.",
    imageUrl: "https://images.unsplash.com/photo-1559563458-527698bf5295?w=600&auto=format&fit=crop"
  },
  {
    id: "marigold",
    name: "French Marigold",
    scientificName: "Tagetes patula",
    category: "flower",
    sunlight: "Full Sun",
    waterFrequency: "Low",
    soilType: "Any Well-draining",
    bloomSeason: "Summer",
    edible: true,
    difficulty: "Easy",
    commonPests: ["Slugs"],
    description: "Bright golden-orange annual flower excellent for companion planting to repel garden pests.",
    imageUrl: "https://images.unsplash.com/photo-1568656458567-d6d729a8f4c4?w=600&auto=format&fit=crop"
  },
  {
    id: "hydrangea",
    name: "Bigleaf Hydrangea",
    scientificName: "Hydrangea macrophylla",
    category: "flower",
    sunlight: "Partial Shade",
    waterFrequency: "High",
    soilType: "Rich, Acidic to Alkaline",
    bloomSeason: "Summer",
    edible: false,
    difficulty: "Moderate",
    commonPests: ["Powdery Mildew"],
    description: "Showy shrub producing large pom-pom blooms whose colors shift based on soil pH.",
    imageUrl: "https://images.unsplash.com/photo-1508610048659-a06b669e3321?w=600&auto=format&fit=crop"
  },
  {
    id: "tulip",
    name: "Dutch Tulip",
    scientificName: "Tulipa",
    category: "flower",
    sunlight: "Full Sun",
    waterFrequency: "Moderate",
    soilType: "Sandy, Well-draining",
    bloomSeason: "Spring",
    edible: false,
    difficulty: "Easy",
    commonPests: ["Squirrels", "Bulb Mites"],
    description: "Iconic spring bulb producing sleek cup-shaped flowers in vivid single and dual colors.",
    imageUrl: "https://images.unsplash.com/photo-1520763185298-1b434c919102?w=600&auto=format&fit=crop"
  },
  {
    id: "jasmine",
    name: "Star Jasmine",
    scientificName: "Trachelospermum jasminoides",
    category: "flower",
    sunlight: "Full Sun",
    waterFrequency: "Moderate",
    soilType: "Loamy, Well-draining",
    bloomSeason: "Spring",
    edible: false,
    difficulty: "Easy",
    commonPests: ["Scale", "Whiteflies"],
    description: "Vigorous evergreen climber producing intense sweet scents from small white star flowers.",
    imageUrl: "https://images.unsplash.com/photo-1534067783941-51c9c23ecefd?w=600&auto=format&fit=crop"
  },
  {
    id: "dahlia",
    name: "Dinnerplate Dahlia",
    scientificName: "Dahlia pinnata",
    category: "flower",
    sunlight: "Full Sun",
    waterFrequency: "High",
    soilType: "Rich, Moist",
    bloomSeason: "Autumn",
    edible: true,
    difficulty: "Hard",
    commonPests: ["Earwigs", "Slugs"],
    description: "Spectacular tuberous perennial producing giant geometric blossoms up to 10 inches across.",
    imageUrl: "https://images.unsplash.com/photo-1563241527-3004b7be0ffd?w=600&auto=format&fit=crop"
  },

  // --- FRUIT PLANTS ---
  {
    id: "strawberry",
    name: "Garden Strawberry",
    scientificName: "Fragaria x ananassa",
    category: "fruit",
    sunlight: "Full Sun",
    waterFrequency: "High",
    soilType: "Slightly Acidic Loam",
    bloomSeason: "Spring",
    edible: true,
    difficulty: "Moderate",
    commonPests: ["Slugs", "Birds"],
    description: "Popular groundcover fruit plant producing sweet red conical berries packed with Vitamin C.",
    imageUrl: "https://images.unsplash.com/photo-1464965911861-746a04b4bca6?w=600&auto=format&fit=crop"
  },
  {
    id: "lemon",
    name: "Meyer Lemon",
    scientificName: "Citrus x meyeri",
    category: "fruit",
    sunlight: "Full Sun",
    waterFrequency: "Moderate",
    soilType: "Sandy Loam",
    bloomSeason: "Year-round",
    edible: true,
    difficulty: "Hard",
    commonPests: ["Citrus Leafminer", "Scale"],
    description: "Compact patio citrus bearing fragrant white flowers and sweet, low-acid lemons.",
    imageUrl: "https://images.unsplash.com/photo-1534531141161-e41d1341d1de?w=600&auto=format&fit=crop"
  },
  {
    id: "blueberry",
    name: "Highbush Blueberry",
    scientificName: "Vaccinium corymbosum",
    category: "fruit",
    sunlight: "Full Sun",
    waterFrequency: "High",
    soilType: "Acidic Peat, Well-draining",
    bloomSeason: "Spring",
    edible: true,
    difficulty: "Moderate",
    commonPests: ["Birds", "Japanese Beetles"],
    description: "Deciduous shrub yielding clusters of deep blue antioxidant-rich summer berries.",
    imageUrl: "https://images.unsplash.com/photo-1498557850523-fd3d118b962e?w=600&auto=format&fit=crop"
  },
  {
    id: "fig",
    name: "Fiddle-leaf Fig / Mission Fig",
    scientificName: "Ficus carica",
    category: "fruit",
    sunlight: "Full Sun",
    waterFrequency: "Low",
    soilType: "Loamy, Well-draining",
    bloomSeason: "Summer",
    edible: true,
    difficulty: "Easy",
    commonPests: ["Nematodes", "Fig Rust"],
    description: "Ancient fruit tree with large lobed leaves yielding sweet, jammy purple-skinned figs.",
    imageUrl: "https://images.unsplash.com/photo-1601493700631-2b16ec4b4716?w=600&auto=format&fit=crop"
  },
  {
    id: "raspberry",
    name: "Heritage Raspberry",
    scientificName: "Rubus idaeus",
    category: "fruit",
    sunlight: "Full Sun",
    waterFrequency: "Moderate",
    soilType: "Rich, Well-draining",
    bloomSeason: "Summer",
    edible: true,
    difficulty: "Easy",
    commonPests: ["Cane Borers", "Aphids"],
    description: "Thorny cane bush delivering heavy crops of aromatic red berries in summer and autumn.",
    imageUrl: "https://images.unsplash.com/photo-1577069861033-55d04ace4ef0?w=600&auto=format&fit=crop"
  },
  {
    id: "apple",
    name: "Gala Apple Tree",
    scientificName: "Malus domestica",
    category: "fruit",
    sunlight: "Full Sun",
    waterFrequency: "Moderate",
    soilType: "Deep Loam",
    bloomSeason: "Spring",
    edible: true,
    difficulty: "Hard",
    commonPests: ["Codling Moth", "Apple Scab"],
    description: "Classic orchard fruit tree producing crisp pinkish-orange sweet dessert apples.",
    imageUrl: "https://images.unsplash.com/photo-1560806887-1e4cd0b6cbd6?w=600&auto=format&fit=crop"
  },
  {
    id: "passionfruit",
    name: "Purple Passionfruit",
    scientificName: "Passiflora edulis",
    category: "fruit",
    sunlight: "Full Sun",
    waterFrequency: "High",
    soilType: "Rich, Moist Loam",
    bloomSeason: "Summer",
    edible: true,
    difficulty: "Moderate",
    commonPests: ["Caterpillars", "Snails"],
    description: "Fast-growing vine with alien-like flowers yielding aromatic tart-sweet tropical fruits.",
    imageUrl: "https://images.unsplash.com/photo-1528821128474-27f963b072b7?w=600&auto=format&fit=crop"
  },
  {
    id: "pomegranate",
    name: "Wonderful Pomegranate",
    scientificName: "Punica granatum",
    category: "fruit",
    sunlight: "Full Sun",
    waterFrequency: "Low",
    soilType: "Drought Tolerant, Any",
    bloomSeason: "Spring",
    edible: true,
    difficulty: "Easy",
    commonPests: ["Whiteflies", "Mealybugs"],
    description: "Resilient Mediterranean shrub with fiery red blossoms producing ruby-jeweled arils.",
    imageUrl: "https://images.unsplash.com/photo-1541344999736-83eca272f6fc?w=600&auto=format&fit=crop"
  },
  {
    id: "blackberry",
    name: "Thornless Blackberry",
    scientificName: "Rubus fruticosus",
    category: "fruit",
    sunlight: "Full Sun",
    waterFrequency: "Moderate",
    soilType: "Slightly Acidic",
    bloomSeason: "Summer",
    edible: true,
    difficulty: "Easy",
    commonPests: ["Stink Bugs"],
    description: "User-friendly thornless bramble delivering dark plump antioxidant berries.",
    imageUrl: "https://images.unsplash.com/photo-1615485290382-441e4d049cb5?w=600&auto=format&fit=crop"
  },
  {
    id: "grape",
    name: "Concord Grape Vine",
    scientificName: "Vitis labrusca",
    category: "fruit",
    sunlight: "Full Sun",
    waterFrequency: "Moderate",
    soilType: "Deep Gravelly Loam",
    bloomSeason: "Spring",
    edible: true,
    difficulty: "Moderate",
    commonPests: ["Grape Phylloxera"],
    description: "Climbing woody vine bearing intense blue-black grapes famous for juice and jellies.",
    imageUrl: "https://images.unsplash.com/photo-1537640538966-79f369143f8f?w=600&auto=format&fit=crop"
  },

  // --- VEGETABLES ---
  {
    id: "cherry-tomato",
    name: "Sweet Million Tomato",
    scientificName: "Solanum lycopersicum",
    category: "vegetable",
    sunlight: "Full Sun",
    waterFrequency: "High",
    soilType: "Rich, Well-draining",
    bloomSeason: "Summer",
    edible: true,
    difficulty: "Moderate",
    commonPests: ["Tomato Hornworm", "Aphids"],
    description: "Prolific producer of small, ultra-sweet red cherry tomatoes grown in long cascading clusters.",
    imageUrl: "https://images.unsplash.com/photo-1592924357228-91a4daadcfea?w=600&auto=format&fit=crop"
  },
  {
    id: "kale",
    name: "Lacinato Tuscan Kale",
    scientificName: "Brassica oleracea var. palmifolia",
    category: "vegetable",
    sunlight: "Partial Shade",
    waterFrequency: "Moderate",
    soilType: "Nitrogen-rich Loam",
    bloomSeason: "Autumn",
    edible: true,
    difficulty: "Easy",
    commonPests: ["Cabbage Loopers"],
    description: "Heirloom Italian kale featuring dark blue-green bumpy leaves rich in iron and vitamins.",
    imageUrl: "https://images.unsplash.com/photo-1524179091875-bf99a9a6af57?w=600&auto=format&fit=crop"
  },
  {
    id: "spinach",
    name: "Bloomsdale Spinach",
    scientificName: "Spinacia oleracea",
    category: "vegetable",
    sunlight: "Partial Shade",
    waterFrequency: "Moderate",
    soilType: "Moist, Well-draining",
    bloomSeason: "Spring",
    edible: true,
    difficulty: "Easy",
    commonPests: ["Leafminers"],
    description: "Fast-growing cool-season green producing crinkled dark-green leaves ideal for salads.",
    imageUrl: "https://images.unsplash.com/photo-1576045057995-568f588f82fb?w=600&auto=format&fit=crop"
  },
  {
    id: "bell-pepper",
    name: "California Wonder Pepper",
    scientificName: "Capsicum annuum",
    category: "vegetable",
    sunlight: "Full Sun",
    waterFrequency: "Moderate",
    soilType: "Warm, Rich Loam",
    bloomSeason: "Summer",
    edible: true,
    difficulty: "Moderate",
    commonPests: ["Cutworms", "Flea Beetles"],
    description: "Blocky bell pepper variety that ripens from dark green to sweet vibrant red.",
    imageUrl: "https://images.unsplash.com/photo-1563565375-f3fdfdbefa83?w=600&auto=format&fit=crop"
  },
  {
    id: "carrot",
    name: "Nantes Carrot",
    scientificName: "Daucus carota subsp. sativus",
    category: "vegetable",
    sunlight: "Full Sun",
    waterFrequency: "Moderate",
    soilType: "Deep Loose Sand",
    bloomSeason: "Spring",
    edible: true,
    difficulty: "Easy",
    commonPests: ["Carrot Rust Fly"],
    description: "Cylindrical sweet root vegetable requiring stone-free soil to develop smooth roots.",
    imageUrl: "https://images.unsplash.com/photo-1598170845058-12ef4a45753b?w=600&auto=format&fit=crop"
  },
  {
    id: "zucchini",
    name: "Black Beauty Zucchini",
    scientificName: "Cucurbita pepo",
    category: "vegetable",
    sunlight: "Full Sun",
    waterFrequency: "High",
    soilType: "Compost-rich",
    bloomSeason: "Summer",
    edible: true,
    difficulty: "Easy",
    commonPests: ["Squash Vine Borer"],
    description: "High-yield summer squash producing tender dark green fruits continuously.",
    imageUrl: "https://images.unsplash.com/photo-1563245372-f21724e3856d?w=600&auto=format&fit=crop"
  },
  {
    id: "radish",
    name: "Cherry Belle Radish",
    scientificName: "Raphanus sativus",
    category: "vegetable",
    sunlight: "Full Sun",
    waterFrequency: "Moderate",
    soilType: "Light, Sandy",
    bloomSeason: "Spring",
    edible: true,
    difficulty: "Easy",
    commonPests: ["Flea Beetles"],
    description: "Ultra-fast maturing root crop ready to harvest in 22 days with crisp pepperiness.",
    imageUrl: "https://images.unsplash.com/photo-1593105544559-ecb03bf76f82?w=600&auto=format&fit=crop"
  },
  {
    id: "cucumber",
    name: "Marketmore Cucumber",
    scientificName: "Cucumis sativus",
    category: "vegetable",
    sunlight: "Full Sun",
    waterFrequency: "High",
    soilType: "Moist, Warm",
    bloomSeason: "Summer",
    edible: true,
    difficulty: "Easy",
    commonPests: ["Cucumber Beetles"],
    description: "Vining vegetable bearing dark green crisp cucumbers perfect for slicing and salads.",
    imageUrl: "https://images.unsplash.com/photo-1449300079323-02e209d9d3a6?w=600&auto=format&fit=crop"
  },
  {
    id: "eggplant",
    name: "Black Beauty Eggplant",
    scientificName: "Solanum melongena",
    category: "vegetable",
    sunlight: "Full Sun",
    waterFrequency: "Moderate",
    soilType: "Warm Rich Soil",
    bloomSeason: "Summer",
    edible: true,
    difficulty: "Moderate",
    commonPests: ["Spider Mites", "Flea Beetles"],
    description: "Warm-loving crop producing glossy deep-purple oval fruits with meaty flesh.",
    imageUrl: "https://images.unsplash.com/photo-1605335870233-a60dfd6a89ef?w=600&auto=format&fit=crop"
  },
  {
    id: "lettuce",
    name: "Butterhead Lettuce",
    scientificName: "Lactuca sativa",
    category: "vegetable",
    sunlight: "Partial Shade",
    waterFrequency: "Moderate",
    soilType: "Fertile, Moist",
    bloomSeason: "Spring",
    edible: true,
    difficulty: "Easy",
    commonPests: ["Slugs", "Aphids"],
    description: "Tender head lettuce featuring soft butter-textured leaves with mild delicate flavor.",
    imageUrl: "https://images.unsplash.com/photo-1556801712-76c8eb07bbc9?w=600&auto=format&fit=crop"
  }
];
